version: '3.7'

services:

  bcc-literature:
    container_name: bcc-literature
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    ports:
      - '8081:8080'
      - '21535:21535'